export interface Country {
  name: string;
  code: string;
  flag: string;
  currency: string;
  symbol: string;
}

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: '+93', flag: '🇦🇫', currency: 'AFN', symbol: '؋' },
  { name: 'Albania', code: '+355', flag: '🇦🇱', currency: 'ALL', symbol: 'L' },
  { name: 'Algeria', code: '+213', flag: '🇩🇿', currency: 'DZD', symbol: 'د.ج' },
  { name: 'Andorra', code: '+376', flag: '🇦🇩', currency: 'EUR', symbol: '€' },
  { name: 'Angola', code: '+244', flag: '🇦🇴', currency: 'AOA', symbol: 'Kz' },
  { name: 'Antigua and Barbuda', code: '+1-268', flag: '🇦🇬', currency: 'XCD', symbol: 'EC$' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷', currency: 'ARS', symbol: '$' },
  { name: 'Armenia', code: '+374', flag: '🇦🇲', currency: 'AMD', symbol: '֏' },
  { name: 'Australia', code: '+61', flag: '🇦🇺', currency: 'AUD', symbol: 'A$' },
  { name: 'Austria', code: '+43', flag: '🇦🇹', currency: 'EUR', symbol: '€' },
  { name: 'Azerbaijan', code: '+994', flag: '🇦🇿', currency: 'AZN', symbol: '₼' },
  { name: 'Bahamas', code: '+1-242', flag: '🇧🇸', currency: 'BSD', symbol: 'B$' },
  { name: 'Bahrain', code: '+973', flag: '🇧🇭', currency: 'BHD', symbol: '.د.ب' },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩', currency: 'BDT', symbol: '৳' },
  { name: 'Barbados', code: '+1-246', flag: '🇧🇧', currency: 'BBD', symbol: 'Bds$' },
  { name: 'Belarus', code: '+375', flag: '🇧🇾', currency: 'BYN', symbol: 'Br' },
  { name: 'Belgium', code: '+32', flag: '🇧🇪', currency: 'EUR', symbol: '€' },
  { name: 'Belize', code: '+501', flag: '🇧🇿', currency: 'BZD', symbol: 'BZ$' },
  { name: 'Benin', code: '+229', flag: '🇧🇯', currency: 'XOF', symbol: 'CFA' },
  { name: 'Bhutan', code: '+975', flag: '🇧🇹', currency: 'BTN', symbol: 'Nu.' },
  { name: 'Bolivia', code: '+591', flag: '🇧🇴', currency: 'BOB', symbol: 'Bs.' },
  { name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦', currency: 'BAM', symbol: 'KM' },
  { name: 'Botswana', code: '+267', flag: '🇧🇼', currency: 'BWP', symbol: 'P' },
  { name: 'Brazil', code: '+55', flag: '🇧🇷', currency: 'BRL', symbol: 'R$' },
  { name: 'Brunei', code: '+673', flag: '🇧🇳', currency: 'BND', symbol: 'B$' },
  { name: 'Bulgaria', code: '+359', flag: '🇧🇬', currency: 'BGN', symbol: 'лв' },
  { name: 'Burkina Faso', code: '+226', flag: '🇧🇫', currency: 'XOF', symbol: 'CFA' },
  { name: 'Burundi', code: '+257', flag: '🇧🇮', currency: 'BIF', symbol: 'FBu' },
  { name: 'Cabo Verde', code: '+238', flag: '🇨🇻', currency: 'CVE', symbol: 'Esc' },
  { name: 'Cambodia', code: '+855', flag: '🇰🇭', currency: 'KHR', symbol: '៛' },
  { name: 'Cameroon', code: '+237', flag: '🇨🇲', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Canada', code: '+1', flag: '🇨🇦', currency: 'CAD', symbol: 'C$' },
  { name: 'Central African Republic', code: '+236', flag: '🇨🇫', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Chad', code: '+235', flag: '🇹🇩', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Chile', code: '+56', flag: '🇨🇱', currency: 'CLP', symbol: '$' },
  { name: 'China', code: '+86', flag: '🇨🇳', currency: 'CNY', symbol: '¥' },
  { name: 'Colombia', code: '+57', flag: '🇨🇴', currency: 'COP', symbol: '$' },
  { name: 'Comoros', code: '+269', flag: '🇰🇲', currency: 'KMF', symbol: 'CF' },
  { name: 'Congo, Democratic Republic of the', code: '+243', flag: '🇨🇩', currency: 'CDF', symbol: 'FC' },
  { name: 'Congo, Republic of the', code: '+242', flag: '🇨🇬', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Costa Rica', code: '+506', flag: '🇨🇷', currency: 'CRC', symbol: '₡' },
  { name: 'Croatia', code: '+385', flag: '🇭🇷', currency: 'EUR', symbol: '€' },
  { name: 'Cuba', code: '+53', flag: '🇨🇺', currency: 'CUP', symbol: '$' },
  { name: 'Cyprus', code: '+357', flag: '🇨🇾', currency: 'EUR', symbol: '€' },
  { name: 'Czechia', code: '+420', flag: '🇨🇿', currency: 'CZK', symbol: 'Kč' },
  { name: 'Denmark', code: '+45', flag: '🇩🇰', currency: 'DKK', symbol: 'kr' },
  { name: 'Djibouti', code: '+253', flag: '🇩🇯', currency: 'DJF', symbol: 'Fdj' },
  { name: 'Dominica', code: '+1-767', flag: '🇩🇲', currency: 'XCD', symbol: 'EC$' },
  { name: 'Dominican Republic', code: '+1-809', flag: '🇩🇴', currency: 'DOP', symbol: 'RD$' },
  { name: 'Ecuador', code: '+593', flag: '🇪🇨', currency: 'USD', symbol: '$' },
  { name: 'Egypt', code: '+20', flag: '🇪🇬', currency: 'EGP', symbol: 'E£' },
  { name: 'El Salvador', code: '+503', flag: '🇸🇻', currency: 'USD', symbol: '$' },
  { name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Eritrea', code: '+291', flag: '🇪🇷', currency: 'ERN', symbol: 'Nfk' },
  { name: 'Estonia', code: '+372', flag: '🇪🇪', currency: 'EUR', symbol: '€' },
  { name: 'Eswatini', code: '+268', flag: '🇸🇿', currency: 'SZL', symbol: 'L' },
  { name: 'Ethiopia', code: '+251', flag: '🇪🇹', currency: 'ETB', symbol: 'Br' },
  { name: 'Fiji', code: '+679', flag: '🇫🇯', currency: 'FJD', symbol: 'FJ$' },
  { name: 'Finland', code: '+358', flag: '🇫🇮', currency: 'EUR', symbol: '€' },
  { name: 'France', code: '+33', flag: '🇫🇷', currency: 'EUR', symbol: '€' },
  { name: 'Gabon', code: '+241', flag: '🇬🇦', currency: 'XAF', symbol: 'FCFA' },
  { name: 'Gambia', code: '+220', flag: '🇬🇲', currency: 'GMD', symbol: 'D' },
  { name: 'Georgia', code: '+995', flag: '🇬🇪', currency: 'GEL', symbol: '₾' },
  { name: 'Germany', code: '+49', flag: '🇩🇪', currency: 'EUR', symbol: '€' },
  { name: 'Ghana', code: '+233', flag: '🇬🇭', currency: 'GHS', symbol: 'GH₵' },
  { name: 'Greece', code: '+30', flag: '🇬🇷', currency: 'EUR', symbol: '€' },
  { name: 'Grenada', code: '+1-473', flag: '🇬🇩', currency: 'XCD', symbol: 'EC$' },
  { name: 'Guatemala', code: '+502', flag: '🇬🇹', currency: 'GTQ', symbol: 'Q' },
  { name: 'Guinea', code: '+224', flag: '🇬🇳', currency: 'GNF', symbol: 'FG' },
  { name: 'Guinea-Bissau', code: '+245', flag: '🇬🇼', currency: 'XOF', symbol: 'CFA' },
  { name: 'Guyana', code: '+592', flag: '🇬🇾', currency: 'GYD', symbol: 'GY$' },
  { name: 'Haiti', code: '+509', flag: '🇭🇹', currency: 'HTG', symbol: 'G' },
  { name: 'Honduras', code: '+504', flag: '🇭🇳', currency: 'HNL', symbol: 'L' },
  { name: 'Hungary', code: '+36', flag: '🇭🇺', currency: 'HUF', symbol: 'Ft' },
  { name: 'Iceland', code: '+354', flag: '🇮🇸', currency: 'ISK', symbol: 'kr' },
  { name: 'India', code: '+91', flag: '🇮🇳', currency: 'INR', symbol: '₹' },
  { name: 'Indonesia', code: '+62', flag: '🇮🇩', currency: 'IDR', symbol: 'Rp' },
  { name: 'Iran', code: '+98', flag: '🇮🇷', currency: 'IRR', symbol: '﷼' },
  { name: 'Iraq', code: '+964', flag: '🇮🇶', currency: 'IQD', symbol: 'ع.د' },
  { name: 'Ireland', code: '+353', flag: '🇮🇪', currency: 'EUR', symbol: '€' },
  { name: 'Israel', code: '+972', flag: '🇮🇱', currency: 'ILS', symbol: '₪' },
  { name: 'Italy', code: '+39', flag: '🇮🇹', currency: 'EUR', symbol: '€' },
  { name: 'Jamaica', code: '+1-876', flag: '🇯🇲', currency: 'JMD', symbol: 'J$' },
  { name: 'Japan', code: '+81', flag: '🇯🇵', currency: 'JPY', symbol: '¥' },
  { name: 'Jordan', code: '+962', flag: '🇯🇴', currency: 'JOD', symbol: 'د.ا' },
  { name: 'Kazakhstan', code: '+7', flag: '🇰🇿', currency: 'KZT', symbol: '₸' },
  { name: 'Kenya', code: '+254', flag: '🇰🇪', currency: 'KES', symbol: 'KSh' },
  { name: 'Kiribati', code: '+686', flag: '🇰🇮', currency: 'AUD', symbol: 'A$' },
  { name: 'Korea, North', code: '+850', flag: '🇰🇵', currency: 'KPW', symbol: '₩' },
  { name: 'Korea, South', code: '+82', flag: '🇰🇷', currency: 'KRW', symbol: '₩' },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼', currency: 'KWD', symbol: 'د.ك' },
  { name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬', currency: 'KGS', symbol: 'лв' },
  { name: 'Laos', code: '+856', flag: '🇱🇦', currency: 'LAK', symbol: '₭' },
  { name: 'Latvia', code: '+371', flag: '🇱🇻', currency: 'EUR', symbol: '€' },
  { name: 'Lebanon', code: '+961', flag: '🇱🇧', currency: 'LBP', symbol: 'ل.ل' },
  { name: 'Lesotho', code: '+266', flag: '🇱🇸', currency: 'LSL', symbol: 'L' },
  { name: 'Liberia', code: '+231', flag: '🇱🇷', currency: 'LRD', symbol: 'L$' },
  { name: 'Libya', code: '+218', flag: '🇱🇾', currency: 'LYD', symbol: 'ل.د' },
  { name: 'Liechtenstein', code: '+423', flag: '🇱🇮', currency: 'CHF', symbol: 'CHF' },
  { name: 'Lithuania', code: '+370', flag: '🇱🇹', currency: 'EUR', symbol: '€' },
  { name: 'Luxembourg', code: '+352', flag: '🇱🇺', currency: 'EUR', symbol: '€' },
  { name: 'Madagascar', code: '+261', flag: '🇲🇬', currency: 'MGA', symbol: 'Ar' },
  { name: 'Malawi', code: '+265', flag: '🇲🇼', currency: 'MWK', symbol: 'MK' },
  { name: 'Malaysia', code: '+60', flag: '🇲🇾', currency: 'MYR', symbol: 'RM' },
  { name: 'Maldives', code: '+960', flag: '🇲🇻', currency: 'MVR', symbol: 'Rf' },
  { name: 'Mali', code: '+223', flag: '🇲🇱', currency: 'XOF', symbol: 'CFA' },
  { name: 'Malta', code: '+356', flag: '🇲🇹', currency: 'EUR', symbol: '€' },
  { name: 'Marshall Islands', code: '+692', flag: '🇲🇭', currency: 'USD', symbol: '$' },
  { name: 'Mauritania', code: '+222', flag: '🇲🇷', currency: 'MRU', symbol: 'UM' },
  { name: 'Mauritius', code: '+230', flag: '🇲🇺', currency: 'MUR', symbol: '₨' },
  { name: 'Mexico', code: '+52', flag: '🇲🇽', currency: 'MXN', symbol: '$' },
  { name: 'Micronesia', code: '+691', flag: '🇫🇲', currency: 'USD', symbol: '$' },
  { name: 'Moldova', code: '+373', flag: '🇲🇩', currency: 'MDL', symbol: 'L' },
  { name: 'Monaco', code: '+377', flag: '🇲🇨', currency: 'EUR', symbol: '€' },
  { name: 'Mongolia', code: '+976', flag: '🇲🇳', currency: 'MNT', symbol: '₮' },
  { name: 'Montenegro', code: '+382', flag: '🇲🇪', currency: 'EUR', symbol: '€' },
  { name: 'Morocco', code: '+212', flag: '🇲🇦', currency: 'MAD', symbol: 'د.م.' },
  { name: 'Mozambique', code: '+258', flag: '🇲🇿', currency: 'MZN', symbol: 'MT' },
  { name: 'Myanmar', code: '+95', flag: '🇲🇲', currency: 'MMK', symbol: 'K' },
  { name: 'Namibia', code: '+264', flag: '🇳🇦', currency: 'NAD', symbol: 'N$' },
  { name: 'Nauru', code: '+674', flag: '🇳🇷', currency: 'AUD', symbol: 'A$' },
  { name: 'Nepal', code: '+977', flag: '🇳🇵', currency: 'NPR', symbol: '₨' },
  { name: 'Netherlands', code: '+31', flag: '🇳🇱', currency: 'EUR', symbol: '€' },
  { name: 'New Zealand', code: '+64', flag: '🇳🇿', currency: 'NZD', symbol: 'NZ$' },
  { name: 'Nicaragua', code: '+505', flag: '🇳🇮', currency: 'NIO', symbol: 'C$' },
  { name: 'Niger', code: '+227', flag: '🇳🇪', currency: 'XOF', symbol: 'CFA' },
  { name: 'Nigeria', code: '+234', flag: '🇳🇬', currency: 'NGN', symbol: '₦' },
  { name: 'North Macedonia', code: '+389', flag: '🇲🇰', currency: 'MKD', symbol: 'ден' },
  { name: 'Norway', code: '+47', flag: '🇳🇴', currency: 'NOK', symbol: 'kr' },
  { name: 'Oman', code: '+968', flag: '🇴🇲', currency: 'OMR', symbol: 'ر.ع.' },
  { name: 'Pakistan', code: '+92', flag: '🇵🇰', currency: 'PKR', symbol: '₨' },
  { name: 'Palau', code: '+680', flag: '🇵🇼', currency: 'USD', symbol: '$' },
  { name: 'Palestine', code: '+970', flag: '🇵🇸', currency: 'ILS', symbol: '₪' },
  { name: 'Panama', code: '+507', flag: '🇵🇦', currency: 'PAB', symbol: 'B/.' },
  { name: 'Papua New Guinea', code: '+675', flag: '🇵🇬', currency: 'PGK', symbol: 'K' },
  { name: 'Paraguay', code: '+595', flag: '🇵🇾', currency: 'PYG', symbol: '₲' },
  { name: 'Peru', code: '+51', flag: '🇵🇪', currency: 'PEN', symbol: 'S/.' },
  { name: 'Philippines', code: '+63', flag: '🇵🇭', currency: 'PHP', symbol: '₱' },
  { name: 'Poland', code: '+48', flag: '🇵🇱', currency: 'PLN', symbol: 'zł' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹', currency: 'EUR', symbol: '€' },
  { name: 'Qatar', code: '+974', flag: '🇶🇦', currency: 'QAR', symbol: 'ر.ق' },
  { name: 'Romania', code: '+40', flag: '🇷🇴', currency: 'RON', symbol: 'lei' },
  { name: 'Russia', code: '+7', flag: '🇷🇺', currency: 'RUB', symbol: '₽' },
  { name: 'Rwanda', code: '+250', flag: '🇷🇼', currency: 'RWF', symbol: 'FRw' },
  { name: 'Saint Kitts and Nevis', code: '+1-869', flag: '🇰🇳', currency: 'XCD', symbol: 'EC$' },
  { name: 'Saint Lucia', code: '+1-758', flag: '🇱🇨', currency: 'XCD', symbol: 'EC$' },
  { name: 'Saint Vincent and the Grenadines', code: '+1-784', flag: '🇻🇨', currency: 'XCD', symbol: 'EC$' },
  { name: 'Samoa', code: '+685', flag: '🇼🇸', currency: 'WST', symbol: 'WS$' },
  { name: 'San Marino', code: '+378', flag: '🇸🇲', currency: 'EUR', symbol: '€' },
  { name: 'Sao Tome and Principe', code: '+239', flag: '🇸🇹', currency: 'STN', symbol: 'Db' },
  { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', currency: 'SAR', symbol: 'ر.س' },
  { name: 'Senegal', code: '+221', flag: '🇸🇳', currency: 'XOF', symbol: 'CFA' },
  { name: 'Serbia', code: '+381', flag: '🇷🇸', currency: 'RSD', symbol: 'дин.' },
  { name: 'Seychelles', code: '+248', flag: '🇸🇨', currency: 'SCR', symbol: '₨' },
  { name: 'Sierra Leone', code: '+232', flag: '🇸🇱', currency: 'SLL', symbol: 'Le' },
  { name: 'Singapore', code: '+65', flag: '🇸🇬', currency: 'SGD', symbol: 'S$' },
  { name: 'Slovakia', code: '+421', flag: '🇸🇰', currency: 'EUR', symbol: '€' },
  { name: 'Slovenia', code: '+386', flag: '🇸🇮', currency: 'EUR', symbol: '€' },
  { name: 'Solomon Islands', code: '+677', flag: '🇸🇧', currency: 'SBD', symbol: 'SI$' },
  { name: 'Somalia', code: '+252', flag: '🇸🇴', currency: 'SOS', symbol: 'Sh.So.' },
  { name: 'South Africa', code: '+27', flag: '🇿🇦', currency: 'ZAR', symbol: 'R' },
  { name: 'South Sudan', code: '+211', flag: '🇸🇸', currency: 'SSP', symbol: '£' },
  { name: 'Spain', code: '+34', flag: '🇪🇸', currency: 'EUR', symbol: '€' },
  { name: 'Sri Lanka', code: '+94', flag: '🇱🇰', currency: 'LKR', symbol: 'Rs' },
  { name: 'Sudan', code: '+249', flag: '🇸🇩', currency: 'SDG', symbol: 'ج.س.' },
  { name: 'Suriname', code: '+597', flag: '🇸🇷', currency: 'SRD', symbol: '$' },
  { name: 'Sweden', code: '+46', flag: '🇸🇪', currency: 'SEK', symbol: 'kr' },
  { name: 'Switzerland', code: '+41', flag: '🇨🇭', currency: 'CHF', symbol: 'CHF' },
  { name: 'Syria', code: '+963', flag: '🇸🇾', currency: 'SYP', symbol: '£S' },
  { name: 'Taiwan', code: '+886', flag: '🇹🇼', currency: 'TWD', symbol: 'NT$' },
  { name: 'Tajikistan', code: '+992', flag: '🇹🇯', currency: 'TJS', symbol: 'ЅМ' },
  { name: 'Tanzania', code: '+255', flag: '🇹🇿', currency: 'TZS', symbol: 'TSh' },
  { name: 'Thailand', code: '+66', flag: '🇹🇭', currency: 'THB', symbol: '฿' },
  { name: 'Timor-Leste', code: '+670', flag: '🇹🇱', currency: 'USD', symbol: '$' },
  { name: 'Togo', code: '+228', flag: '🇹🇬', currency: 'XOF', symbol: 'CFA' },
  { name: 'Tonga', code: '+676', flag: '🇹🇴', currency: 'TOP', symbol: 'T$' },
  { name: 'Trinidad and Tobago', code: '+1-868', flag: '🇹🇹', currency: 'TTD', symbol: 'TT$' },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳', currency: 'TND', symbol: 'د.ت' },
  { name: 'Turkey', code: '+90', flag: '🇹🇷', currency: 'TRY', symbol: '₺' },
  { name: 'Turkmenistan', code: '+993', flag: '🇹🇲', currency: 'TMT', symbol: 'T' },
  { name: 'Tuvalu', code: '+688', flag: '🇹🇻', currency: 'AUD', symbol: 'A$' },
  { name: 'Uganda', code: '+256', flag: '🇺🇬', currency: 'UGX', symbol: 'USh' },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', currency: 'UAH', symbol: '₴' },
  { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪', currency: 'AED', symbol: 'د.إ' },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧', currency: 'GBP', symbol: '£' },
  { name: 'United States', code: '+1', flag: '🇺🇸', currency: 'USD', symbol: '$' },
  { name: 'Uruguay', code: '+598', flag: '🇺🇾', currency: 'UYU', symbol: '$U' },
  { name: 'Uzbekistan', code: '+998', flag: '🇺🇿', currency: 'UZS', symbol: 'лв' },
  { name: 'Vanuatu', code: '+678', flag: '🇻🇺', currency: 'VUV', symbol: 'VT' },
  { name: 'Vatican City', code: '+39-06', flag: '🇻🇦', currency: 'EUR', symbol: '€' },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪', currency: 'VES', symbol: 'Bs.S' },
  { name: 'Vietnam', code: '+84', flag: '🇻🇳', currency: 'VND', symbol: '₫' },
  { name: 'Yemen', code: '+967', flag: '🇾🇪', currency: 'YER', symbol: '﷼' },
  { name: 'Zambia', code: '+260', flag: '🇿🇲', currency: 'ZMW', symbol: 'ZK' },
  { name: 'Zimbabwe', code: '+263', flag: '🇿🇼', currency: 'ZWL', symbol: '$' }
];

export function getCountryFromPhone(phone?: string): Country {
  if (!phone) {
    return { name: 'United States', code: '+1', flag: '🇺🇸', currency: 'USD', symbol: '$' };
  }
  const cleanPhone = phone.trim();
  let bestMatch: Country | null = null;
  for (const country of COUNTRIES) {
    if (cleanPhone.startsWith(country.code)) {
      if (!bestMatch || country.code.length > bestMatch.code.length) {
        bestMatch = country;
      }
    }
  }
  return bestMatch || { name: 'United States', code: '+1', flag: '🇺🇸', currency: 'USD', symbol: '$' };
}

